In [3]:
import numpy as np
import pandas as pd

DATAFRAME--collection of multiple series

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

#### Creating a DataFrame  ####

In [6]:
df2=pd.DataFrame(data)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [13]:
df2=pd.DataFrame(data_list)
coulmns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=coulmns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selection and Indexing of Columns ####

In [15]:
df2[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [17]:
## Adding Column ##

In [19]:
df2["Des"]=["Doc","Eng","Teacher","Doc"]
df2

    Name  Age      City  Salary      Des
0   John   28  New York   65000      Doc
1   Anna   34     Paris   70000      Eng
2  Peter   29    Berlin   62000  Teacher
3  Linda   42    London   85000      Doc

In [20]:
## Removing Coulmn ##

In [21]:
df2.drop("Des",axis=1,inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selecting Rows  ####

In [22]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [23]:
### Selecting Subsets of Rows and Columns

In [24]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [25]:
df2.loc[[0,1]][["Name","Age"]]

   Name  Age
0  John   28
1  Anna   34

In [26]:
df2.loc[[2,3]][["City","Salary"]]

     City  Salary
2  Berlin   62000
3  London   85000

In [27]:
#### Conditional Selection

In [29]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [30]:
df2[(df2["Age"]>30)&(df2["City"]=="Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000