In [5]:
import numpy as np
import pandas as pd

In [6]:
## Loading the Data

In [7]:
df=pd.read_csv(r'anime.csv')

In [8]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [9]:

#make a new column for episode count

In [10]:
df.loc[1]['Title']

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

In [19]:
def extract_episode(txt):
    check=False
    data=""
    for i in txt:
        if i=="(":
            check=True
            continue
            
        if i==")":
            break
        if check==True: 
            data+=i
            
        
    return data

In [20]:
df["Episodes"]=df["Title"].apply(extract_episode)

In [22]:
df["Episodes"]=df["Episodes"].str.replace("eps","")

In [24]:
df["Episodes"]=df["Episodes"].astype(int)

In [33]:
df.head()

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [ ]:
#make a new column for time stamp

In [28]:
def extraction_time(txt):
    check =False
    data=""
    for i in range(len(txt)):
        if txt[i]==")":
            for j in range(i+1,i+20):
                 data+=txt[j]
    return data

In [31]:
df ["Total Time"]=df["Title"].apply(extraction_time)
df.head()

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [32]:
from dateutil.relativedelta import relativedelta
from datetime import datetime

def calculate_total_months(period):
    try:
        start_str, end_str = period.split(' - ')
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')
        r = relativedelta(end_date, start_date)
        return r.years * 12 + r.months + 1  # +1 to include the starting month
    except:
        return None

df['Months'] = df['Total Time'].apply(calculate_total_months)
df.head()

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [ ]:
#which anime has the highest score

In [34]:
df[df["Score"]==df["Score"].max()]["Title"]

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: str

In [ ]:
#give me top 5 highest scoring anime

In [35]:
df["Title"].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: str

In [ ]:
#which anime has the highest episode count

In [36]:
df[df["Episodes"]==df["Episodes"].max()]

,Rank,Title,Score,Episodes,Total Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

In [ ]:
#animes with top 5 episode count

In [37]:
df.sort_values(by="Episodes", ascending=False).head(5)

,Rank,Title,Score,Episodes,Total Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,36
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,18

In [38]:
#which is the longest running anime

In [40]:
df[df["Months"]==df["Months"].max()]["Title"]

11    Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
Name: Title, dtype: str